filter:
    excluded_paths: [vendor/*, spec/*, features/*]

tools:
    php_pdepend:
        excluded_dirs:
            - vendor
            - spec
            - features
    external_code_coverage: true
    php_cpd: true
    php_loc: true
    php_mess_detector: true
    php_analyzer: true
    php_code_sniffer:
        config:
            standard: "PSR2"
